"use strict";(function(jQuery,window,undefined){"use strict";var matched,browser;jQuery.uaMatch=function(ua){ua=ua.toLowerCase();var match=/(opr)[\/]([\w.]+)/.exec(ua)||/(chrome)[ \/]([\w.]+)/.exec(ua)||/(version)[ \/]([\w.]+).*(safari)[ \/]([\w.]+)/.exec(ua)||/(webkit)[ \/]([\w.]+)/.exec(ua)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(ua)||/(msie) ([\w.]+)/.exec(ua)||ua.indexOf("trident")>=0&&/(rv)(?::| )([\w.]+)/.exec(ua)||ua.indexOf("compatible")<0&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(ua)||[];var platform_match=/(ipad)/.exec(ua)||/(iphone)/.exec(ua)||/(android)/.exec(ua)||/(windows phone)/.exec(ua)||/(win)/.exec(ua)||/(mac)/.exec(ua)||/(linux)/.exec(ua)||/(cros)/i.exec(ua)||[];return{browser:match[3]||match[1]||"",version:match[2]||"0",platform:platform_match[0]||""};};matched=jQuery.uaMatch(window.navigator.userAgent);browser={};if(matched.browser){browser[matched.browser]=true;browser.version=matched.version;browser.versionNumber=parseInt(matched.version);}
if(matched.platform){browser[matched.platform]=true;}
if(browser.android||browser.ipad||browser.iphone||browser["windows phone"]){browser.mobile=true;}
if(browser.cros||browser.mac||browser.linux||browser.win){browser.desktop=true;}
if(browser.chrome||browser.opr||browser.safari){browser.webkit=true;}
if(browser.rv)
{var ie="msie";matched.browser=ie;browser[ie]=true;}
if(browser.opr)
{var opera="opera";matched.browser=opera;browser[opera]=true;}
if(browser.safari&&browser.android)
{var android="android";matched.browser=android;browser[android]=true;}
browser.name=matched.browser;browser.platform=matched.platform;jQuery.browser=browser;})(jQuery,window);(function($){$.fn.getCursorPosition=function(){var input=this.get(0);if(!input)return;if('selectionStart'in input){return input.selectionStart;}else if(document.selection){input.focus();var sel=document.selection.createRange();var selLen=document.selection.createRange().text.length;sel.moveStart('character',-input.value.length);return sel.text.length- selLen;}}})(jQuery);(function($){$.fn.setCursorPosition=function(pos){if(this.setSelectionRange){this.setSelectionRange(pos,pos);}else if(this.createTextRange){var range=this.createTextRange();range.collapse(true);if(pos<0){pos=$(this).val().length+ pos;}
range.moveEnd('character',pos);range.moveStart('character',pos);range.select();}}})(jQuery);(function($,document,window,undefined){$.fn.insertAtCaret=function(text){return this.each(function(){var input=this,scrollPos,strPos=0,before,after,range;if(!((input.tagName&&input.tagName.toLowerCase()==="textarea")||(input.tagName&&input.tagName.toLowerCase()==="input"&&input.type.toLowerCase()==="text"))){return;}
scrollPos=input.scrollTop;if($.browser.msie){input.focus();range=document.selection.createRange();range.moveStart('character',-input.value.length);strPos=range.text.length;}else{strPos=input.selectionStart;}
before=(input.value).substring(0,strPos);after=(input.value).substring(strPos,input.value.length);input.value=before+ text+ after;strPos=strPos+ text.length;if($.browser.msie){range=document.selection.createRange();range.moveStart('character',strPos);range.moveEnd('character',0);range.select();}else{input.selectionStart=strPos;input.selectionEnd=strPos;}
input.scrollTop=scrollPos;});};})(jQuery,document,window);if('webkitSpeechRecognition'in window){$('#search_input').after('<span id="microphone_element" class="input-group-addon cursor-pointer"><i class="fa fa-microphone fa-lg"></i></span>');$('#microphone_element').click(function(e){var textArea=$('#search_input');var recognition=new webkitSpeechRecognition();recognition.continuous=true;recognition.interimResults=true;window.interimResult='';recognition.onstart=function(event){textArea.val('');};recognition.onend=function(event){};recognition.onresult=function(event){var pos=textArea.getCursorPosition()- window.interimResult.length;textArea.val(textArea.val().replace(window.interimResult,''));window.interimResult='';textArea.setCursorPosition(pos);for(var i=event.resultIndex;i<event.results.length;++i){console.log(event.results[i][0].transcript);if(event.results[i].isFinal){textArea.insertAtCaret(event.results[i][0].transcript);var e=$.Event("keydown");e.keyCode=13;$("#search_input").trigger(e);recognition.stop();}else{textArea.insertAtCaret(event.results[i][0].transcript+'\u200B');window.interimResult+=event.results[i][0].transcript+'\u200B';}}};recognition.start();});}
String.prototype.trunc=String.prototype.trunc||function(n){return this.length>n?this.substr(0,n-1)+'&hellip;':this;};var result_trailer='&nbsp;&nbsp;';$(document).on("click",".glyphicon",function(){$(this).css({'color':'black'}).siblings().css({'color':'#A21B29'});});$(document).on("click",".edit-pencil",function(){$('.feedback-input').remove();$(this).parent().append('<input class="form-control btn-xlg feedback-input" type="text" placeholder="Type your feedback and press enter when done">');$('.feedback-input').focus();});$(document).on("keydown",".feedback-input",function(e){if(e.keyCode==13){e.preventDefault();$('.feedback-submitted').remove();$(this).parent().append('&nbsp;&nbsp;<span class="color-green feedback-submitted">Thank you, your feedback has been submitted.</span>');$(this).remove();}});var show_error_for_result=function(id,error_msg){var error=$('<div class="alert alert-danger" role="alert">'+ error_msg+'</div>').css('display','none');$('#results-'+ id).append(error);error.slideDown();};var showModal=function(title,message){if(title!==undefined&&message!==undefined){$('#statusModalLabel').text(title);$('#statusModalContent').text(message);}
$('.statusModal').modal('show');};if(document.location.hash==='#registered'){showModal('Success!','You are registered for Slack integration. Please use /peruse inside of Slack to ask questions.');}
var addSlackIntegration=function(){var userName=$('#slackUsername').val();var teamDomain=$('#slackTeamDomain').val();var slackToken=null;if($('#slackToken').length===1){slackToken=$('#slackToken').val();}
var payload={'slackUsername':userName,'slackTeamDomain':teamDomain};if(slackToken!==null){payload['slackToken']=slackToken;}
$.ajax({type:'POST',url:'/register_slackbot',data:JSON.stringify(payload),contentType:'application/json; charset=utf-8',success:function(response){$('.registerSlackbotModal').modal('hide');if(response.status!==undefined){window.location.href+='#registered';location.reload();}else{if(response.error!==undefined){showModal('Error Registering Slack Slash Command',response.error);}else{showModal('Error','Invalid registration response');}}}});};$('#addSlackIntegrationBtn').click(function(){addSlackIntegration();});$('#slackTeamDomain').blur(function(e){var slackTeamDomain=e.target.value.replace(/[^a-zA-Z0-9\-]/g,'');var slackTeamLink=$('#slackTeamLink');var url='https://'+ slackTeamDomain+'.slack.com/services/new/slash-commands';slackTeamLink.attr('href',url);slackTeamLink.text(url);});var generate_view=function(arg){var result_id=arg.rid;var id=arg.uid;var filename=arg.filename;var parentObj=arg.dom_root;var type=arg.type;$('#btn-'+ result_id).prop('disabled',true);var load_icon=$('#load-icon-'+ result_id);load_icon.fadeIn();$.ajax({type:'POST',url:'/generate_view',data:JSON.stringify({'type':type,'id':id,'filename':filename}),contentType:'application/json; charset=utf-8',success:function(response){var results=response.results;load_icon.fadeOut();if(results===undefined){show_error_for_result(id,"An error occured in generating the document view");}else if(results.error!==undefined){show_error_for_result(id,"An error has occurred: "+ results.error);}else{var box_id='box-view-'+ result_id;var boxView=$('<div class="box-view" id="'+ box_id+'" style="height:400px"></div>');parentObj.append(boxView);var viewer=Crocodoc.createViewer('#'+ box_id,{url:results.urls.assets,plugins:{}});viewer.load();boxView.slideDown();}}});};var file_is_supported=function(filename){var supported_ext=["pdf","doc","docx","ppt","pptx","xls","xlsx","txt","py","js","xml","html","css","md","pl","c","m","json"];var file_ext=/[^.]+$/.exec(filename);if(file_ext&&supported_ext.indexOf(file_ext[0])!==-1){return true;}
if(filename.indexOf("&exportFormat=pdf")!==-1){return true;}
return false;};var search_enabled=true;var search_keydown=function(e){e.preventDefault();if($('#search_input').val()===''){$('#search_input').attr('placeholder','you have to enter something to perform a search');return;}
$('#prefix').html('<i class="fa fa-circle-o-notch fa-spin color-green"></i>');search_enabled=false;$.ajax({type:'POST',url:'/search',data:JSON.stringify({'terms':$('#search_input').val(),'page':window.location.pathname}),contentType:'application/json; charset=utf-8',error:function(){search_enabled=true;$('#prefix').html('<i class="fa fa-search fa-lg"></i>');$('#prefix').append(" Cannot handle this search now, please try another.");},success:function(response){search_enabled=true;if(response['did_you_mean']){$('#did_you_mean').html('Did you mean: '+response['did_you_mean']+'?');}else{$('#did_you_mean').html('');}
$('#prefix').html('<i class="fa fa-search fa-lg"></i>');if(response['results'].length){var result_id=0;var result_stream=[];$.each(response['results'],function(index,value){if(value['label']){value['label']=value['label']+': ';}
var result=$('<div id="results-'+ result_id+'" class="bs-example">');if(['dropbox','box','gdrive','cell_answer'].indexOf(value['type'])!=-1){if(!file_is_supported(value['filename'])){var viewBtn='';}else{var viewBtn=$('<span>&nbsp;</span><i class="fa fa-circle-o-notch fa-spin color-green" id="load-icon-'+ result_id+'" style="display:none"></i>&nbsp;<button id="btn-'+ result_id+'" type="button" class="btn btn-default btn-xs">'+'<span class="glyphicon glyphicon-eye-open text-primary" aria-hidden="true"></span>&nbsp;<span class="text-primary">Click to preview</span></button>');if(value['type']=='cell_answer'){var arg={rid:result_id,uid:value.id,filename:value.filename,dom_root:result,type:value.location_storage};}else{var arg={rid:result_id,uid:value.id,filename:value.filename,dom_root:result,type:value.type};}
console.log(arg);viewBtn.click(function(){generate_view(arg);});}}
if('title'in value){if('url'in value&&value['url']){result.append('&nbsp;<mark><strong><a target="_blank" href="'+value['url']+'">'+value['title']+'</a></strong></mark>'+value['content']);}else{result.append('&nbsp;<mark><strong>'+value['title']+'</strong></mark>'+value['content']);}}
if('heading'in value&&value['heading']){if('url'in value&&value['url']){result.append('<mark><strong><a target="_blank" href="'+ value['url']+'">'+ value['heading']+'</a></strong></mark><br />'+ value['label']+ value['content']);}else{result.append('<mark><strong>'+ value['heading']+'</strong></mark><br />'+ value['label']+ value['content']);}}else if(value['content']){result.append(value['label']+value['content']);}
if('location'in value){var downloadBtn='<span class="glyphicon glyphicon-circle-arrow-down text-primary" aria-hidden="true"></span>&nbsp;<small><a target="_blank" href="'+ value['location']+'">Download</a></small></div>';}else{var downloadBtn=''}
var thumbs_down='';var thumbs_up='';if(value['type']=='cell_answer'){if(typeof(Intercom)!='undefined'){thumbs_down=$('<button id="btn-'+value.answer_id+'down" class="btn btn-default btn-xs" type="button"><i class="fa fa-thumbs-o-down"></i>&nbsp;<span><small>Wrong answer</small></span></button>');thumbs_down.click(function(){intercom_thumbs('down',value.answer_id,$('#search_input').val(),value['label']+value['content'],value['filename']);});thumbs_up=$('<button id="btn-'+value.answer_id+'up" class="btn btn-default btn-xs" type="button"><i class="fa fa-thumbs-o-up"></i>&nbsp;<span><small>Good answer</small></span></button>');thumbs_up.click(function(){intercom_thumbs('up',value.answer_id,$('#search_input').val(),value['label']+value['content'],value['filename']);});}
result.append('<br /><small class="text-muted">file: '+value['filename']+'</small>');}
result.append(viewBtn);result.append(downloadBtn);result.append(thumbs_down);result.append(thumbs_up);result.append(result_trailer);result_stream.push(result);result_id++;});$('.mastfoot').css({'visibility':'hidden'});$('#results').empty().append(result_stream).css({'visibility':'visible'});$("[data-toggle='tooltip']").tooltip();}else{$('#results').empty();$('#prefix').append(" No results, please try another query.");}}});search_request_event($('#search_input').val());};$('#search_input').keydown(function(e){if(e.keyCode==13&&search_enabled){search_keydown(e);}});$('#prefix').click(function(e){search_keydown(e);});if(typeof(USER)!=='undefined'){analytics.identify(USER.id,{email:USER.email});var intercom_thumbs=function(judgment,id,query,answer,filename){$('#btn-'+ id+'up').prop('disabled',true);$('#btn-'+ id+'down').prop('disabled',true);$('#btn-'+ id+ judgment).html('Your feedback helps Peruse improve answer quality!');if(judgment=='down'){$('#btn-'+ id+'up').remove();$('#btn-'+ id+ judgment).after('If you have a suggestion on how the answer can be improved, please click on the question mark chat icon on the bottom right of the page.');}else{$('#btn-'+ id+'down').remove();}
analytics.track('qa-cell-answer-'+judgment,{query:query.trunc(60).toString(),answer:answer.trunc(60).toString(),filename:filename},{integrations:{'All':false,'Intercom':true}});analytics.track('feedback',{category:'qa-cell-answer',label:judgment},{integrations:{'All':false,'Google Analytics':true}});};var search_request_event=function(query){analytics.track('search',{query:query.trunc(100).toString()},{integrations:{'All':false,'Intercom':true}});analytics.track('search',{category:'user'},{integrations:{'All':false,'Google Analytics':true}});};}else{var intercom_thumbs=function(judgment,id,query,answer,filename){};var search_request_event=function(query){};}
$('#try_it_button').click(function(e){lock.showSignup({container:'try_it_block',callbackURL:AUTH0_LOGIN_CALLBACK,dict:{signup:{footerText:'By signing up, you agree to our <a href="/terms" target="_new">terms of service</a> and <a href="/privacy" target="_new">privacy policy</a>.'}}});});(function(){'use strict';if(navigator.userAgent.match(/IEMobile\/10\.0/)){var msViewportStyle=document.createElement('style')
msViewportStyle.appendChild(document.createTextNode('@-ms-viewport{width:auto!important}'))
document.querySelector('head').appendChild(msViewportStyle)}})();